import 'models.dart';

const teamWorldCupRecordSourceName =
    'API-Football 2026 team cards + historical World Cup record';
const teamWorldCupRecordSourceUrl =
    'https://www.api-football.com/news/post/fifa-world-cup-2026-lineups-all-teams-coaches-and-players';

const Map<String, TeamWorldCupRecord> teamWorldCupRecords = {
  'mex': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 17,
    played: 60,
    wins: 17,
    draws: 15,
    losses: 28,
    goalsScored: 62,
    goalsConceded: 101,
  ),
  'rsa': TeamWorldCupRecord(
    firstWorldCup: 1998,
    participationsBefore2026: 3,
    played: 9,
    wins: 2,
    draws: 4,
    losses: 3,
    goalsScored: 11,
    goalsConceded: 16,
  ),
  'kor': TeamWorldCupRecord(
    firstWorldCup: 1954,
    participationsBefore2026: 11,
    played: 38,
    wins: 7,
    draws: 10,
    losses: 21,
    goalsScored: 39,
    goalsConceded: 78,
  ),
  'cze': TeamWorldCupRecord(
    firstWorldCup: 2006,
    participationsBefore2026: 1,
    played: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsScored: 3,
    goalsConceded: 4,
  ),
  'can': TeamWorldCupRecord(
    firstWorldCup: 1986,
    participationsBefore2026: 2,
    played: 6,
    wins: 0,
    draws: 0,
    losses: 6,
    goalsScored: 2,
    goalsConceded: 12,
  ),
  'sui': TeamWorldCupRecord(
    firstWorldCup: 1934,
    participationsBefore2026: 12,
    played: 41,
    wins: 14,
    draws: 8,
    losses: 19,
    goalsScored: 55,
    goalsConceded: 73,
  ),
  'qat': TeamWorldCupRecord(
    firstWorldCup: 2022,
    participationsBefore2026: 1,
    played: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 1,
    goalsConceded: 7,
  ),
  'bih': TeamWorldCupRecord(
    firstWorldCup: 2014,
    participationsBefore2026: 1,
    played: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsScored: 4,
    goalsConceded: 4,
  ),
  'bra': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 22,
    played: 114,
    wins: 76,
    draws: 19,
    losses: 19,
    goalsScored: 237,
    goalsConceded: 108,
  ),
  'mar': TeamWorldCupRecord(
    firstWorldCup: 1970,
    participationsBefore2026: 6,
    played: 23,
    wins: 5,
    draws: 7,
    losses: 11,
    goalsScored: 20,
    goalsConceded: 27,
  ),
  'hai': TeamWorldCupRecord(
    firstWorldCup: 1974,
    participationsBefore2026: 1,
    played: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 2,
    goalsConceded: 14,
  ),
  'sco': TeamWorldCupRecord(
    firstWorldCup: 1954,
    participationsBefore2026: 8,
    played: 23,
    wins: 4,
    draws: 7,
    losses: 12,
    goalsScored: 25,
    goalsConceded: 41,
  ),
  'usa': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 11,
    played: 37,
    wins: 9,
    draws: 8,
    losses: 20,
    goalsScored: 40,
    goalsConceded: 68,
  ),
  'par': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 8,
    played: 27,
    wins: 7,
    draws: 10,
    losses: 10,
    goalsScored: 30,
    goalsConceded: 38,
  ),
  'aus': TeamWorldCupRecord(
    firstWorldCup: 1974,
    participationsBefore2026: 6,
    played: 20,
    wins: 4,
    draws: 4,
    losses: 12,
    goalsScored: 17,
    goalsConceded: 37,
  ),
  'tur': TeamWorldCupRecord(
    firstWorldCup: 1954,
    participationsBefore2026: 2,
    played: 10,
    wins: 5,
    draws: 1,
    losses: 4,
    goalsScored: 20,
    goalsConceded: 17,
  ),
  'ger': TeamWorldCupRecord(
    firstWorldCup: 1934,
    participationsBefore2026: 20,
    played: 112,
    wins: 68,
    draws: 21,
    losses: 23,
    goalsScored: 232,
    goalsConceded: 130,
  ),
  'cur': TeamWorldCupRecord(
    firstWorldCup: 2026,
    participationsBefore2026: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsScored: 0,
    goalsConceded: 0,
  ),
  'civ': TeamWorldCupRecord(
    firstWorldCup: 2006,
    participationsBefore2026: 3,
    played: 9,
    wins: 3,
    draws: 1,
    losses: 5,
    goalsScored: 13,
    goalsConceded: 14,
  ),
  'ecu': TeamWorldCupRecord(
    firstWorldCup: 2002,
    participationsBefore2026: 4,
    played: 13,
    wins: 5,
    draws: 2,
    losses: 6,
    goalsScored: 14,
    goalsConceded: 14,
  ),
  'ned': TeamWorldCupRecord(
    firstWorldCup: 1934,
    participationsBefore2026: 11,
    played: 55,
    wins: 30,
    draws: 14,
    losses: 11,
    goalsScored: 96,
    goalsConceded: 52,
  ),
  'jpn': TeamWorldCupRecord(
    firstWorldCup: 1998,
    participationsBefore2026: 7,
    played: 25,
    wins: 7,
    draws: 6,
    losses: 12,
    goalsScored: 25,
    goalsConceded: 33,
  ),
  'tun': TeamWorldCupRecord(
    firstWorldCup: 1978,
    participationsBefore2026: 6,
    played: 18,
    wins: 3,
    draws: 5,
    losses: 10,
    goalsScored: 14,
    goalsConceded: 26,
  ),
  'swe': TeamWorldCupRecord(
    firstWorldCup: 1934,
    participationsBefore2026: 12,
    played: 51,
    wins: 19,
    draws: 13,
    losses: 19,
    goalsScored: 80,
    goalsConceded: 73,
  ),
  'bel': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 14,
    played: 51,
    wins: 21,
    draws: 10,
    losses: 20,
    goalsScored: 69,
    goalsConceded: 74,
  ),
  'egy': TeamWorldCupRecord(
    firstWorldCup: 1934,
    participationsBefore2026: 3,
    played: 7,
    wins: 0,
    draws: 2,
    losses: 5,
    goalsScored: 5,
    goalsConceded: 12,
  ),
  'irn': TeamWorldCupRecord(
    firstWorldCup: 1978,
    participationsBefore2026: 6,
    played: 18,
    wins: 3,
    draws: 4,
    losses: 11,
    goalsScored: 13,
    goalsConceded: 31,
  ),
  'nzl': TeamWorldCupRecord(
    firstWorldCup: 1982,
    participationsBefore2026: 2,
    played: 6,
    wins: 0,
    draws: 3,
    losses: 3,
    goalsScored: 4,
    goalsConceded: 14,
  ),
  'esp': TeamWorldCupRecord(
    firstWorldCup: 1934,
    participationsBefore2026: 16,
    played: 67,
    wins: 31,
    draws: 17,
    losses: 19,
    goalsScored: 108,
    goalsConceded: 75,
  ),
  'cpv': TeamWorldCupRecord(
    firstWorldCup: 2026,
    participationsBefore2026: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsScored: 0,
    goalsConceded: 0,
  ),
  'ksa': TeamWorldCupRecord(
    firstWorldCup: 1994,
    participationsBefore2026: 6,
    played: 19,
    wins: 4,
    draws: 2,
    losses: 13,
    goalsScored: 14,
    goalsConceded: 44,
  ),
  'uru': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 14,
    played: 59,
    wins: 25,
    draws: 13,
    losses: 21,
    goalsScored: 89,
    goalsConceded: 76,
  ),
  'fra': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 16,
    played: 73,
    wins: 39,
    draws: 14,
    losses: 20,
    goalsScored: 136,
    goalsConceded: 85,
  ),
  'sen': TeamWorldCupRecord(
    firstWorldCup: 2002,
    participationsBefore2026: 3,
    played: 12,
    wins: 5,
    draws: 3,
    losses: 4,
    goalsScored: 16,
    goalsConceded: 17,
  ),
  'nor': TeamWorldCupRecord(
    firstWorldCup: 1938,
    participationsBefore2026: 3,
    played: 8,
    wins: 2,
    draws: 3,
    losses: 3,
    goalsScored: 7,
    goalsConceded: 8,
  ),
  'irq': TeamWorldCupRecord(
    firstWorldCup: 1986,
    participationsBefore2026: 1,
    played: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 1,
    goalsConceded: 4,
  ),
  'arg': TeamWorldCupRecord(
    firstWorldCup: 1930,
    participationsBefore2026: 18,
    played: 88,
    wins: 47,
    draws: 17,
    losses: 24,
    goalsScored: 152,
    goalsConceded: 101,
  ),
  'alg': TeamWorldCupRecord(
    firstWorldCup: 1982,
    participationsBefore2026: 4,
    played: 13,
    wins: 3,
    draws: 3,
    losses: 7,
    goalsScored: 13,
    goalsConceded: 19,
  ),
  'aut': TeamWorldCupRecord(
    firstWorldCup: 1934,
    participationsBefore2026: 7,
    played: 29,
    wins: 12,
    draws: 4,
    losses: 13,
    goalsScored: 43,
    goalsConceded: 47,
  ),
  'jor': TeamWorldCupRecord(
    firstWorldCup: 2026,
    participationsBefore2026: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsScored: 0,
    goalsConceded: 0,
  ),
  'por': TeamWorldCupRecord(
    firstWorldCup: 1966,
    participationsBefore2026: 8,
    played: 35,
    wins: 17,
    draws: 6,
    losses: 12,
    goalsScored: 61,
    goalsConceded: 41,
  ),
  'uzb': TeamWorldCupRecord(
    firstWorldCup: 2026,
    participationsBefore2026: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsScored: 0,
    goalsConceded: 0,
  ),
  'col': TeamWorldCupRecord(
    firstWorldCup: 1962,
    participationsBefore2026: 6,
    played: 22,
    wins: 9,
    draws: 3,
    losses: 10,
    goalsScored: 32,
    goalsConceded: 30,
  ),
  'cod': TeamWorldCupRecord(
    firstWorldCup: 1974,
    participationsBefore2026: 1,
    played: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 0,
    goalsConceded: 14,
  ),
  'eng': TeamWorldCupRecord(
    firstWorldCup: 1950,
    participationsBefore2026: 16,
    played: 74,
    wins: 32,
    draws: 22,
    losses: 20,
    goalsScored: 104,
    goalsConceded: 68,
  ),
  'cro': TeamWorldCupRecord(
    firstWorldCup: 1998,
    participationsBefore2026: 6,
    played: 30,
    wins: 13,
    draws: 8,
    losses: 9,
    goalsScored: 43,
    goalsConceded: 33,
  ),
  'gha': TeamWorldCupRecord(
    firstWorldCup: 2006,
    participationsBefore2026: 4,
    played: 15,
    wins: 5,
    draws: 3,
    losses: 7,
    goalsScored: 18,
    goalsConceded: 23,
  ),
  'pan': TeamWorldCupRecord(
    firstWorldCup: 2018,
    participationsBefore2026: 1,
    played: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsScored: 2,
    goalsConceded: 11,
  ),
};
